// SpellEngine.swift — Spell-check engine for Clavi iOS keyboard
// Mirrors SpellEngine.kt. Reads uncompressed SPLV binary dict files.
//
// Dict format "SPLV" (generated by tools/build_spell_dict.py):
//   4 bytes  magic "SPLV"
//   u32 LE   word_count
//   u32 LE   hash_table_size
//   word list: word_count × [u8 len][UTF-8 bytes]   sorted lexicographically
//   hash table: hash_table_size × u64 FNV-1a, open-addressing, 0 = empty

import Foundation

struct SpellSuggestion {
    let word: String
    let confidence: Float
}

final class SpellEngine {
    private var words: [String] = []
    private var hashTable: [UInt64] = []
    private var ready = false

    // QWERTY adjacency
    private let qwertyAdjacent: [Character: Set<Character>] = [
        "q": ["w","a","s"],
        "w": ["q","e","a","s","d"],
        "e": ["w","r","s","d","f"],
        "r": ["e","t","d","f","g"],
        "t": ["r","y","f","g","h"],
        "y": ["t","u","g","h","j"],
        "u": ["y","i","h","j","k"],
        "i": ["u","o","j","k","l"],
        "o": ["i","p","k","l"],
        "p": ["o","l"],
        "a": ["q","w","s","z"],
        "s": ["a","w","e","d","z","x"],
        "d": ["s","e","r","f","x","c"],
        "f": ["d","r","t","g","c","v"],
        "g": ["f","t","y","h","v","b"],
        "h": ["g","y","u","j","b","n"],
        "j": ["h","u","i","k","n","m"],
        "k": ["j","i","o","l","m"],
        "l": ["k","o","p"],
        "z": ["a","s","x"],
        "x": ["z","s","d","c"],
        "c": ["x","d","f","v"],
        "v": ["c","f","g","b"],
        "b": ["v","g","h","n"],
        "n": ["b","h","j","m"],
        "m": ["n","j","k"],
    ]

    // Ukrainian ЙЦУКЕН → QWERTY physical position
    private let cyrillicToQwerty: [Character: Character] = [
        "й":"q","ц":"w","у":"e","к":"r","е":"t","н":"y","г":"u","ш":"i","щ":"o","з":"p",
        "ф":"a","і":"s","в":"d","а":"f","п":"g","р":"h","о":"j","л":"k","д":"l",
        "я":"z","ч":"x","с":"c","м":"v","и":"b","т":"n","ь":"m",
    ]

    init(lang: String) {
        DispatchQueue.global(qos: .background).async { [weak self] in
            guard let self = self else { return }
            guard let url = Bundle.main.url(forResource: lang, withExtension: "bin",
                                            subdirectory: "spell"),
                  let data = try? Data(contentsOf: url) else { return }
            self.parse(data: data)
        }
    }

    // ── Public API ──

    func isCorrect(_ word: String) -> Bool {
        guard ready else { return true }
        return hashContains(Fnv1a.hash64(word.lowercased()))
    }

    func correct(_ word: String) -> SpellSuggestion? {
        guard ready else { return nil }
        let lower = word.lowercased()
        guard lower.count >= 3 else { return nil }
        guard !hashContains(Fnv1a.hash64(lower)) else { return nil }

        var candidates: [String: Float] = [:]
        let chars = Array(lower)
        let alphabet: [Character] = Array("abcdefghijklmnopqrstuvwxyz")

        for i in chars.indices {
            let c = chars[i]

            // Delete
            var deleted = chars; deleted.remove(at: i)
            if deleted.count >= 2 { record(String(deleted), cost: 1.0, into: &candidates) }

            // Transpose
            if i < chars.count - 1 {
                var swapped = chars; swapped.swapAt(i, i + 1)
                record(String(swapped), cost: 0.6, into: &candidates)
            }

            // Replace
            for r in alphabet {
                if r == c { continue }
                let cost = proximityCost(c, r)
                var replaced = chars; replaced[i] = r
                record(String(replaced), cost: cost, into: &candidates)
            }
        }

        // Insert
        for i in 0...chars.count {
            for ins in alphabet {
                var inserted = chars
                inserted.insert(ins, at: i)
                record(String(inserted), cost: 1.0, into: &candidates)
            }
        }

        guard !candidates.isEmpty else { return nil }

        let wordCount = Float(words.count)
        let best = candidates
            .filter { hashContains(Fnv1a.hash64($0.key)) }
            .min { lhs, rhs in
                let lRank = Float(frequencyRank(lhs.key)) / wordCount
                let rRank = Float(frequencyRank(rhs.key)) / wordCount
                return lhs.value * 0.7 + lRank * 0.3 < rhs.value * 0.7 + rRank * 0.3
            }

        guard let best = best else { return nil }
        let confidence = min(max(1.0 - best.value, 0), 1)
        if confidence < 0.3 { return nil }
        return SpellSuggestion(word: best.key, confidence: confidence)
    }

    func complete(prefix: String) -> [String] {
        guard ready, prefix.count >= 2 else { return [] }
        let lower = prefix.lowercased()
        var result: [String] = []
        var i = lowerBound(lower)
        while i < words.count && result.count < 3 {
            if words[i].hasPrefix(lower) {
                result.append(words[i])
            } else if words[i] > lower && !words[i].hasPrefix(lower) {
                break
            }
            i += 1
        }
        return result
    }

    // ── Internal helpers ──

    private func record(_ word: String, cost: Float, into map: inout [String: Float]) {
        guard word.count >= 2, word.count <= 15 else { return }
        if let existing = map[word] {
            if cost < existing { map[word] = cost }
        } else {
            map[word] = cost
        }
    }

    private func proximityCost(_ a: Character, _ b: Character) -> Float {
        let qa = cyrillicToQwerty[a] ?? a
        let qb = cyrillicToQwerty[b] ?? b
        return (qwertyAdjacent[qa]?.contains(qb) ?? false) ? 0.3 : 1.0
    }

    private func frequencyRank(_ word: String) -> Int {
        let idx = lowerBound(word)
        return (idx < words.count && words[idx] == word) ? idx : words.count
    }

    private func lowerBound(_ prefix: String) -> Int {
        var lo = 0, hi = words.count
        while lo < hi {
            let mid = (lo + hi) >> 1
            if words[mid] < prefix { lo = mid + 1 } else { hi = mid }
        }
        return lo
    }

    private func hashContains(_ h: UInt64) -> Bool {
        guard ready, !hashTable.isEmpty else { return false }
        let size = hashTable.count
        var idx = Int(h % UInt64(size))
        while true {
            let slot = hashTable[idx]
            if slot == 0 { return false }
            if slot == h { return true }
            idx = (idx + 1) % size
        }
    }

    // ── Binary parser ──

    private func parse(data: Data) {
        guard data.count > 12 else { return }

        // Magic
        guard let magic = String(bytes: data[0..<4], encoding: .ascii), magic == "SPLV" else { return }
        var offset = 4

        let wordCount = Int(data.readUInt32LE(at: offset)); offset += 4
        let tableSize = Int(data.readUInt32LE(at: offset)); offset += 4

        // Word list
        var wordList: [String] = []
        wordList.reserveCapacity(wordCount)
        for _ in 0..<wordCount {
            guard offset < data.count else { break }
            let len = Int(data[offset]); offset += 1
            guard offset + len <= data.count else { break }
            if let word = String(bytes: data[offset..<(offset + len)], encoding: .utf8) {
                wordList.append(word)
            }
            offset += len
        }

        // Hash table
        var table: [UInt64] = []
        table.reserveCapacity(tableSize)
        for _ in 0..<tableSize {
            guard offset + 8 <= data.count else { break }
            table.append(data.readUInt64LE(at: offset))
            offset += 8
        }

        words = wordList
        hashTable = table
        ready = true
    }
}

// ── Data reading helpers ──

private extension Data {
    func readUInt32LE(at offset: Int) -> UInt32 {
        let b = self
        return UInt32(b[offset]) |
               UInt32(b[offset+1]) << 8 |
               UInt32(b[offset+2]) << 16 |
               UInt32(b[offset+3]) << 24
    }

    func readUInt64LE(at offset: Int) -> UInt64 {
        let b = self
        return UInt64(b[offset]) |
               UInt64(b[offset+1]) << 8 |
               UInt64(b[offset+2]) << 16 |
               UInt64(b[offset+3]) << 24 |
               UInt64(b[offset+4]) << 32 |
               UInt64(b[offset+5]) << 40 |
               UInt64(b[offset+6]) << 48 |
               UInt64(b[offset+7]) << 56
    }
}
