package com.clavi.keyboard

import android.content.Context
import java.io.IOException
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.util.zip.GZIPInputStream

/**
 * Spell-check engine backed by a compact binary dictionary (.bin, gzip'd).
 *
 * Features:
 *  - isCorrect()  — O(1) FNV-1a 64-bit hash lookup
 *  - correct()    — Norvig-style single-edit candidates ranked by QWERTY key proximity
 *  - complete()   — top-3 prefix completions via binary search on the sorted word list
 *
 * Dict format "SPLV" (generated by tools/build_spell_dict.py):
 *   4 bytes  magic "SPLV"
 *   u32 LE   word_count
 *   u32 LE   hash_table_size
 *   word list: word_count × [u8 len][UTF-8 bytes]   sorted by (len, alpha)
 *   hash table: hash_table_size × u64 FNV-1a, open-addressing, 0 = empty
 *
 * Thread safety: load() is called once in a background thread; all public methods
 * are safe to call from the main thread after loading is complete (volatile flag).
 */
data class SpellSuggestion(val word: String, val confidence: Float)

class SpellEngine(private val context: Context, private val lang: String) {

    @Volatile private var ready = false

    private lateinit var words: Array<String>   // sorted word list (frequency proxy = index)
    private lateinit var hashTable: LongArray   // open-addressing FNV-1a table

    // QWERTY row adjacency — physical neighbours on a US layout
    private val QWERTY_ADJACENT: Map<Char, Set<Char>> = mapOf(
        'q' to setOf('w', 'a', 's'),
        'w' to setOf('q', 'e', 'a', 's', 'd'),
        'e' to setOf('w', 'r', 's', 'd', 'f'),
        'r' to setOf('e', 't', 'd', 'f', 'g'),
        't' to setOf('r', 'y', 'f', 'g', 'h'),
        'y' to setOf('t', 'u', 'g', 'h', 'j'),
        'u' to setOf('y', 'i', 'h', 'j', 'k'),
        'i' to setOf('u', 'o', 'j', 'k', 'l'),
        'o' to setOf('i', 'p', 'k', 'l'),
        'p' to setOf('o', 'l'),
        'a' to setOf('q', 'w', 's', 'z'),
        's' to setOf('a', 'w', 'e', 'd', 'z', 'x'),
        'd' to setOf('s', 'e', 'r', 'f', 'x', 'c'),
        'f' to setOf('d', 'r', 't', 'g', 'c', 'v'),
        'g' to setOf('f', 't', 'y', 'h', 'v', 'b'),
        'h' to setOf('g', 'y', 'u', 'j', 'b', 'n'),
        'j' to setOf('h', 'u', 'i', 'k', 'n', 'm'),
        'k' to setOf('j', 'i', 'o', 'l', 'm'),
        'l' to setOf('k', 'o', 'p'),
        'z' to setOf('a', 's', 'x'),
        'x' to setOf('z', 's', 'd', 'c'),
        'c' to setOf('x', 'd', 'f', 'v'),
        'v' to setOf('c', 'f', 'g', 'b'),
        'b' to setOf('v', 'g', 'h', 'n'),
        'n' to setOf('b', 'h', 'j', 'm'),
        'm' to setOf('n', 'j', 'k'),
    )

    // Ukrainian ЙЦУКЕН → physical QWERTY key (for proximity cost across scripts)
    private val CYRILLIC_TO_QWERTY: Map<Char, Char> = mapOf(
        'й' to 'q', 'ц' to 'w', 'у' to 'e', 'к' to 'r', 'е' to 't',
        'н' to 'y', 'г' to 'u', 'ш' to 'i', 'щ' to 'o', 'з' to 'p',
        'ф' to 'a', 'і' to 's', 'в' to 'd', 'а' to 'f', 'п' to 'g',
        'р' to 'h', 'о' to 'j', 'л' to 'k', 'д' to 'l',
        'я' to 'z', 'ч' to 'x', 'с' to 'c', 'м' to 'v', 'и' to 'b',
        'т' to 'n', 'ь' to 'm',
    )

    init {
        Thread {
            try {
                load()
            } catch (_: IOException) {
                // Graceful degradation: keyboard still works, autocorrect silently absent
            }
        }.start()
    }

    // ── Public API ──

    fun isCorrect(word: String): Boolean {
        if (!ready) return true   // don't flag anything until loaded
        return hashContains(fnv1a64(word.lowercase()))
    }

    fun correct(word: String): SpellSuggestion? {
        if (!ready) return null
        val lower = word.lowercase()
        if (lower.length < 3) return null
        if (hashContains(fnv1a64(lower))) return null  // already correct

        val candidates = mutableMapOf<String, Float>()  // word → min cost

        // Generate all single-edit candidates
        for (i in lower.indices) {
            val c = lower[i]

            // Delete
            val deleted = lower.removeRange(i, i + 1)
            if (deleted.length >= 2) recordCandidate(deleted, 1.0f, candidates)

            // Transpose (swap with next)
            if (i < lower.length - 1) {
                val swapped = lower.toCharArray().also { a ->
                    val tmp = a[i]; a[i] = a[i + 1]; a[i + 1] = tmp
                }.concatToString()
                recordCandidate(swapped, 0.6f, candidates)
            }

            // Replace with adjacent keys
            for (replacement in 'a'..'z') {
                if (replacement == c) continue
                val cost = proximityCost(c, replacement)
                val replaced = lower.toCharArray().also { it[i] = replacement }.concatToString()
                recordCandidate(replaced, cost, candidates)
            }
            // Also try replacing with Cyrillic (for cross-script near-misses)
            for ((cyr, qwerty) in CYRILLIC_TO_QWERTY) {
                val cost = proximityCost(c, qwerty)
                if (cost <= 0.3f) {
                    val replaced = lower.toCharArray().also { it[i] = cyr }.concatToString()
                    recordCandidate(replaced, cost, candidates)
                }
            }
        }

        // Insert
        for (i in 0..lower.length) {
            for (insertion in 'a'..'z') {
                val inserted = lower.substring(0, i) + insertion + lower.substring(i)
                recordCandidate(inserted, 1.0f, candidates)
            }
        }

        if (candidates.isEmpty()) return null

        // Rank: score = costWeight * 0.7 + frequencyRank * 0.3
        val wordCount = words.size.toFloat()
        val best = candidates.entries
            .filter { hashContains(fnv1a64(it.key)) }
            .minByOrNull { (w, cost) ->
                val rank = frequencyRank(w) / wordCount
                cost * 0.7f + rank * 0.3f
            } ?: return null

        val confidence = (1.0f - best.value).coerceIn(0f, 1f)
        if (confidence < 0.3f) return null
        return SpellSuggestion(best.key, confidence)
    }

    fun complete(prefix: String): List<String> {
        if (!ready || prefix.length < 2) return emptyList()
        val lower = prefix.lowercase()
        val start = lowerBound(lower)
        val result = mutableListOf<String>()
        var i = start
        while (i < words.size && result.size < 3) {
            if (words[i].startsWith(lower)) result.add(words[i])
            else if (words[i] > lower && !words[i].startsWith(lower)) break
            i++
        }
        return result
    }

    // ── Internal helpers ──

    private fun recordCandidate(word: String, cost: Float, map: MutableMap<String, Float>) {
        if (word.length < 2 || word.length > 15) return
        val existing = map[word]
        if (existing == null || cost < existing) map[word] = cost
    }

    private fun proximityCost(a: Char, b: Char): Float {
        val qa = CYRILLIC_TO_QWERTY[a] ?: a
        val qb = CYRILLIC_TO_QWERTY[b] ?: b
        return if (QWERTY_ADJACENT[qa]?.contains(qb) == true) 0.3f else 1.0f
    }

    private fun frequencyRank(word: String): Int {
        val idx = lowerBound(word)
        return if (idx < words.size && words[idx] == word) idx else words.size
    }

    private fun lowerBound(prefix: String): Int {
        var lo = 0; var hi = words.size
        while (lo < hi) {
            val mid = (lo + hi) ushr 1
            if (words[mid] < prefix) lo = mid + 1 else hi = mid
        }
        return lo
    }

    private fun hashContains(h: Long): Boolean {
        if (!ready) return false
        val size = hashTable.size
        val mask = (size - 1).toLong()
        var idx = (h and mask).toInt()
        while (true) {
            val slot = hashTable[idx]
            if (slot == 0L) return false
            if (slot == h) return true
            idx = ((idx + 1) and (size - 1))
        }
    }

    private fun fnv1a64(word: String): Long {
        var h = -3750763034362895579L  // 14695981039346656037 as signed Long
        for (b in word.encodeToByteArray()) {
            h = h xor b.toLong()
            h *= 1099511628211L
        }
        return if (h == 0L) 1L else h
    }

    // ── Loader ──

    private fun load() {
        val assetPath = "spell/$lang.bin"
        val raw = context.assets.open(assetPath).use { stream ->
            GZIPInputStream(stream).readBytes()
        }
        val buf = ByteBuffer.wrap(raw).order(ByteOrder.LITTLE_ENDIAN)

        // Magic
        val magic = ByteArray(4).also { buf.get(it) }
        check(String(magic) == "SPLV") { "Bad magic in $assetPath" }

        val wordCount = buf.int
        val tableSize = buf.int

        // Word list
        val wordList = Array(wordCount) { "" }
        for (i in 0 until wordCount) {
            val len = buf.get().toInt() and 0xFF
            val bytes = ByteArray(len).also { buf.get(it) }
            wordList[i] = String(bytes, Charsets.UTF_8)
        }

        // Hash table
        val table = LongArray(tableSize) { buf.long }

        words = wordList
        hashTable = table
        ready = true
    }
}
