#include "clavi/hook.hpp"
#include "clavi/word_buffer.hpp"

#include <uiohook.h>
#include <atomic>
#include <cstdio>
#include <cstdarg>

namespace clavi {

// ── Module-level state (used from libuiohook C callbacks) ──────────────────

static std::atomic<bool> g_running{false};
static std::atomic<bool> g_suppress{false}; // suppress during retype
static HookCallbacks     g_callbacks;
static WordBuffer*       g_word_buf = nullptr;

// ── libuiohook event dispatcher ─────────────────────────────────────────────

static void dispatch_event(uiohook_event* const ev) {
    if (!ev) return;

    // Suppress events generated by our own retype (prevents re-entrancy)
    if (g_suppress.load(std::memory_order_relaxed)) return;

    // Read modifier state from the event mask (more reliable than manual tracking)
    const bool ctrl = (ev->mask & (MASK_CTRL_L | MASK_CTRL_R)) != 0;
    const bool shift = (ev->mask & (MASK_SHIFT_L | MASK_SHIFT_R)) != 0;
    const bool alt = (ev->mask & (MASK_ALT_L | MASK_ALT_R)) != 0;

    switch (ev->type) {

        case EVENT_KEY_PRESSED: {
            const uint16_t kc = ev->data.keyboard.keycode;

            // Skip bare modifier presses
            if (kc == VC_CONTROL_L || kc == VC_CONTROL_R ||
                kc == VC_SHIFT_L   || kc == VC_SHIFT_R   ||
                kc == VC_ALT_L     || kc == VC_ALT_R     ||
                kc == VC_META_L    || kc == VC_META_R) {
                break;
            }

            // Ctrl+Z → undo (without Shift)
            if (ctrl && !shift && !alt && kc == VC_Z) {
                if (g_word_buf) g_word_buf->feed_clear();
                if (g_callbacks.on_undo) g_callbacks.on_undo();
                break;
            }

            // Ctrl+Shift+Space → toggle
            if (ctrl && shift && !alt && kc == VC_SPACE) {
                if (g_word_buf) g_word_buf->feed_clear();
                if (g_callbacks.on_toggle) g_callbacks.on_toggle();
                break;
            }

            // Ctrl+T → translit mode toggle
            if (ctrl && !shift && !alt && kc == VC_T) {
                if (g_word_buf) g_word_buf->feed_clear();
                if (g_callbacks.on_translit_toggle) g_callbacks.on_translit_toggle();
                break;
            }

            // Backspace → erase last codepoint in buffer
            if (!ctrl && !alt && kc == VC_BACKSPACE) {
                if (g_word_buf) g_word_buf->feed_backspace();
                break;
            }

            // Enter / Return → flush current word
            if (!ctrl && !alt && (kc == VC_ENTER || kc == VC_KP_ENTER)) {
                if (g_word_buf) g_word_buf->flush();
                break;
            }

            // Escape → discard current word
            if (kc == VC_ESCAPE) {
                if (g_word_buf) g_word_buf->feed_clear();
                break;
            }

            // Tab → flush (word boundary)
            if (!ctrl && !alt && kc == VC_TAB) {
                if (g_word_buf) g_word_buf->flush();
                break;
            }

            // Any modified keystroke (Ctrl+X, Alt+F4 etc.) clears the buffer
            if (ctrl || alt) {
                if (g_word_buf) g_word_buf->feed_clear();
            }
            break;
        }

        case EVENT_KEY_RELEASED:
            break; // modifiers tracked via ev->mask, nothing to do

        case EVENT_KEY_TYPED: {
            // EVENT_KEY_TYPED delivers the Unicode BMP character.
            const uint16_t ch = ev->data.keyboard.keychar;
            if (ch == CHAR_UNDEFINED || ctrl || alt) break;

            if (g_word_buf) g_word_buf->feed_codepoint(static_cast<uint32_t>(ch));
            break;
        }

        default:
            break;
    }
}

static bool logger_callback(unsigned int level, const char* fmt, ...) {
    if (level == LOG_LEVEL_ERROR) {
        va_list args;
        va_start(args, fmt);
        std::vfprintf(stderr, fmt, args);
        va_end(args);
        std::fputc('\n', stderr);
    }
    return level != LOG_LEVEL_ERROR;
}

// ── Hook ────────────────────────────────────────────────────────────────────

Hook::~Hook() { stop(); }

void Hook::run(HookCallbacks callbacks) {
    g_callbacks = std::move(callbacks);

    WordBuffer wbuf;
    wbuf.set_commit_callback([](const std::string& word) {
        if (!g_callbacks.on_word_commit) return;
        g_suppress.store(true, std::memory_order_relaxed);
        g_callbacks.on_word_commit(word);
        g_suppress.store(false, std::memory_order_relaxed);
    });
    g_word_buf  = &wbuf;
    g_running.store(true);
    running_.store(true);

    hook_set_logger_proc(&logger_callback);
    hook_set_dispatch_proc(&dispatch_event);

    hook_run(); // blocks until hook_stop() is called

    g_word_buf = nullptr;
    running_.store(false);
    g_running.store(false);
}

void Hook::stop() noexcept {
    if (g_running.load()) hook_stop();
}

} // namespace clavi
